"use client";
import {sessionFetch} from "../lib/session";
import {useEffect,useRef,useState} from 'react';
import {ArrowRight,Check,Copy,Gift,BookOpen} from 'lucide-react';
import BirthFields,{readBirthFields} from './BirthFields';
import ChartTabs from './ChartTabs';
import {freeCategories,birthCategories,type FreeReading,type AttendanceState} from '../data/free-fortune';
import {loginHref} from '../lib/service-links';
import './free-fortune.css';
async function api(path:string,body?:object) {
 const r=await (path==='session'?sessionFetch():fetch('/api/yeongnyangi/'+path,{cache:'no-store',credentials:'same-origin',...(body?{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify(body)}:{})}));
 const data=await r.json();if(!r.ok)throw Object.assign(new Error(data.message||'연결을 마치지 못했어요. 다시 시도해 주세요.'),{code:data.code});return data;
}
function TypedReading({reading}:{reading:FreeReading}) {
 const text=reading.paragraphs.join('\n\n'),[count,setCount]=useState(0),[copied,setCopied]=useState(false),[error,setError]=useState('');
 useEffect(()=>{if(matchMedia('(prefers-reduced-motion: reduce)').matches){setCount(text.length);return;}setCount(0);const t=setInterval(()=>setCount(n=>{if(n>=text.length){clearInterval(t);return text.length;}return Math.min(n+3,text.length);}),24);return()=>clearInterval(t);},[text]);
 return <article className="free-reading"><div className="free-reading-heading"><div><p>{reading.day} · {reading.kind==='reflection'?'질문·상징 해설':reading.kind==='symbolic'?'상징 리딩':'계산 근거가 있는 해설'}</p><h3>{reading.title}</h3></div>{count<text.length&&<button type="button" onClick={()=>setCount(text.length)}>바로 읽기</button>}</div>{reading.charts&&reading.charts.length>0&&<div className="free-chart"><h4>먼저 계산된 차트를 볼게.</h4><p>무료 운세도 같은 계산 근거를 숨기지 않아. 아래 차트와 만세력을 펼쳐 확인해 봐.</p><ChartTabs charts={reading.charts}/></div>}<div className="free-summary"><strong>짧게 말하면</strong><p>{reading.summary}</p></div><h4>영냥이가 조금 더 풀어줄게.</h4><div className="room-daily-message" aria-hidden="true">{text.slice(0,count).split('\n\n').map((p,i)=><p key={i}>{p}</p>)}</div><div className="sr-only">{reading.paragraphs.map((p,i)=><p key={i}>{p}</p>)}</div><details className="free-evidence"><summary>어떤 근거로 읽었을까?</summary><dl>{reading.basis.map((b,i)=><div key={i}><dt>{b.label}</dt><dd>{b.value}</dd></div>)}</dl>{reading.limitations.map((x,i)=><p key={i}>{x}</p>)}</details><details className="free-prompt"><summary>이 운세의 전문가 프롬프트</summary><p>현재 운세의 계산값과 전용 해석 규칙을 담았어. 확인한 뒤 원하는 상담 도구에 직접 붙여넣어 줘. 자동으로 전송하지 않아.</p><pre tabIndex={0} aria-label="복사할 상담 프롬프트">{reading.prompt}</pre><button type="button" onClick={async()=>{try{await navigator.clipboard.writeText(reading.prompt);setCopied(true);setError('');}catch{setError('위 문장을 직접 선택해 복사해 주세요.');}}}>{copied?<Check size={17}/>:<Copy size={17}/>} {copied?'복사했어':'프롬프트 복사하기'}</button>{error&&<p role="alert">{error}</p>}</details></article>;
}
export default function DailyWords() {
 const [state,setState]=useState<AttendanceState|null>(null),[login,setLogin]=useState(false),[error,setError]=useState(''),[busy,setBusy]=useState(false),[category,setCategory]=useState('basic'),[reading,setReading]=useState<FreeReading|null>(null),[profile,setProfile]=useState(''),[profiles,setProfiles]=useState<{id:string;created_at:number}[]>([]),[showBirth,setShowBirth]=useState(false),[reaction,setReaction]=useState<'idle'|'receive'|'unimpressed'|'done'>('idle'),[reduced,setReduced]=useState(false),[draft,setDraft]=useState<Record<string,string>>({}),[notice,setNotice]=useState('');
 const lock=useRef(false),version=useRef(0),timers=useRef<ReturnType<typeof setTimeout>[]>([]),currentDay=useRef('');
 const config=freeCategories.find(c=>c.id===category)!;
 async function refresh(){const s=await api('attendance');currentDay.current=s.day;setState(s);setProfiles((await api('profiles')).profiles);}
 function failure(e:unknown){const err=e as Error&{code?:string};setError(err.message);if(err.code==='SESSION_REQUIRED'){setLogin(true);setState(null);setReading(null);}if(err.code==='FREE_PROFILE_REQUIRED')setShowBirth(true);if(err.code==='DAILY_PASS_REQUIRED'){setReading(null);void refresh().catch(()=>{});}}
 useEffect(()=>{let active=true;(async()=>{try{await api('session',{});if(active)await refresh();}catch(e){if(active)failure(e);}})();const media=matchMedia('(prefers-reduced-motion: reduce)');setReduced(media.matches);const changed=()=>setReduced(media.matches);media.addEventListener('change',changed);const tick=setInterval(()=>{const day=new Date(Date.now()+9*3600000).toISOString().slice(0,10);if(currentDay.current&&day!==currentDay.current){version.current++;setReading(null);setReaction('idle');void refresh().catch(failure);}},15000);return()=>{active=false;version.current++;clearInterval(tick);timers.current.forEach(clearTimeout);media.removeEventListener('change',changed);};},[]);
 useEffect(()=>{const v=++version.current;setReading(null);setError('');setDraft({});if(!state?.unlocked)return;api('free/reading?category='+category).then(d=>{if(v===version.current)setReading(d.result);}).catch(e=>{if(v===version.current)failure(e);});},[category,state?.day,state?.unlocked]);
 async function action(kind:'attendance'|'free/unlock') {if(lock.current)return;lock.current=true;setBusy(true);setError('');try{const s=await api(kind,{});setState(s);setNotice(kind==='attendance'?(s.awarded?'출석했어. 멸치 한 마리가 쌓였어.':'오늘 출석은 이미 했어.'):'오늘의 모든 이야기가 열렸어.');if(s.newlyUnlocked){setReaction(reduced?'unimpressed':'receive');if(!reduced)timers.current.push(setTimeout(()=>setReaction('unimpressed'),400),setTimeout(()=>setReaction('done'),1300));}}catch(e){failure(e);}finally{lock.current=false;setBusy(false);}}
 async function saveProfile(e:React.FormEvent<HTMLFormElement>){e.preventDefault();if(lock.current)return;lock.current=true;setBusy(true);setError('');try{const personA=readBirthFields(new FormData(e.currentTarget));if(!personA.birthPlace)throw Error('출생지를 검색하고 결과에서 선택해 줘.');const p=await api('profiles',{domain:'saju',input:{personA,readingMode:'personal',question:''}});setProfile(p.id);await refresh();setShowBirth(false);setNotice('출생 정보를 보관했어. 원하는 이야기를 골라봐.');}catch(e){failure(e);}finally{lock.current=false;setBusy(false);}}
 async function generate(e:React.FormEvent){e.preventDefault();if(lock.current)return;lock.current=true;setBusy(true);setError('');const v=++version.current;try{const result=await api('free/reading',{category,profileId:profile||undefined,draft});if(v===version.current)setReading(result);}catch(e){if(v===version.current)failure(e);}finally{lock.current=false;setBusy(false);}}
 const extra=config.fields.filter(f=>!['question','topic','context','tone','depth','avoid'].includes(f.id)&&!/(birth|calendar|gender|partner|name|system|period)/i.test(f.id));
 return <section id="daily" className="room-daily free-fortune" aria-labelledby="daily-title"><div className="free-welcome"><div className={'anchovy-cat '+reaction}><img src={reaction==='unimpressed'||reaction==='receive'?'/_soulcat/assets/fish/reaction-anchovy.webp':'/_soulcat/assets/expression-calm.webp'} width={240} height={240} alt={reaction==='unimpressed'?'멸치를 내려다보며 미묘하게 불만족스러운 영냥이':'이야기를 기다리는 영냥이'}/>{reaction==='receive'&&<img className="incoming-anchovy" src="/_soulcat/assets/fish/anchovy.webp" width={64} height={32} alt=""/>}</div><div><h2 id="daily-title">멸치 한 마리,<br/>오늘의 이야기.</h2><p className="anchovy-dialogue">{reaction!=='idle'?'……멸치 한 마리. 흠, 일단 받을게. 운세는 제대로 봐줄 테니까.':'운세는 무료로 봐줄게. 그래도 멸치 한 마리는 줘야지. 출석하고 받아 와.'}</p></div></div>
 <div className="attendance-bar"><div className="anchovy-balance"><img src="/_soulcat/assets/fish/anchovy.webp" width={72} height={36} alt="멸치"/><span>내 멸치<strong>{state?`${state.balance}마리`:'로그인 후 확인'}</strong></span></div><div className="attendance-actions">{login?<a className="free-primary" href={loginHref('/yeongnyangi/room/#daily')}>로그인하고 출석하기<ArrowRight size={17}/></a>:state?<><button type="button" onClick={()=>action('attendance')} disabled={busy||state.attended}>{state.attended?<Check size={17}/>:<Gift size={17}/>} {state.attended?'오늘 출석 완료':'출석하고 멸치 받기'}</button><button type="button" className="free-primary" onClick={()=>action('free/unlock')} disabled={busy||state.unlocked||state.balance<1}>{state.unlocked?<BookOpen size={17}/>:<ArrowRight size={17}/>} {state.unlocked?'오늘의 16종 열림':'멸치 1마리 건네기'}</button></>:<p>출석 수첩을 확인하고 있어.</p>}</div></div><p className="free-policy">하루 한 번 출석으로 멸치 1마리. 1마리로 오늘의 16종 전체를 열어줘. 남은 멸치는 쌓아둘게. 하루는 한국 시간 자정에 바뀌어.</p><p className="free-status" role="status">{notice}</p>
 {error&&<div className="free-error" role="alert"><p>{error}</p>{!login&&<button type="button" disabled={busy} onClick={()=>refresh().then(()=>setError('')).catch(failure)}>상태 다시 확인</button>}</div>}
 <div className="free-categories" role="group" aria-label="무료 운세 16종">{freeCategories.map(c=><button type="button" key={c.id} aria-pressed={category===c.id} onClick={()=>setCategory(c.id)}>{c.label.replace(' 프롬프트','')}</button>)}</div>
 {!state?.unlocked?<div className="free-locked"><h3>{config.label}</h3><p>{config.description}</p><p>출석 멸치로 오늘의 이야기를 열어줘. 금액을 결제하는 과정은 없어.</p></div>:<><div className="free-profile"><label>이번 이야기에 사용할 본인 프로필<select value={profile} onChange={e=>setProfile(e.target.value)}><option value="">직접 선택해 주세요</option>{profiles.map((p,i)=><option key={p.id} value={p.id}>{i+1}번째 프로필 · {new Date(p.created_at).toLocaleDateString('ko-KR')}</option>)}</select></label><button type="button" onClick={()=>setShowBirth(!showBirth)}>{showBirth?'입력 접기':'출생 정보 새로 입력하기'}</button><small>상대방 정보는 자동 선택하지 않아. 이미 읽은 운세는 그날 처음 확인한 정보로 유지돼.</small></div>{showBirth&&<form onSubmit={saveProfile} className="fortune-form free-birth-form"><BirthFields/><button className="free-primary" disabled={busy}>이 출생 정보 보관하기<Check size={17}/></button></form>}
 {reading?<TypedReading key={reading.day+reading.category} reading={reading}/>:<form onSubmit={generate} className="free-question"><h3>{config.label}</h3><p>{config.description}</p><label>궁금한 이야기<textarea rows={3} value={draft.question||''} onChange={e=>setDraft({...draft,question:e.target.value})} maxLength={900} placeholder="지금 내가 살펴볼 선택은 무엇일까?"/></label>{extra.length>0&&<details><summary>이 분야의 질문 단서 더하기</summary>{extra.map(f=><label key={f.id}>{f.label}<input type="text" value={draft[f.id]||''} onChange={e=>setDraft({...draft,[f.id]:e.target.value})} maxLength={500}/></label>)}</details>}{birthCategories.has(category)&&!profile&&<p>본인 프로필을 선택하거나 출생 정보를 알려줘.</p>}<button className="free-primary" disabled={busy||(birthCategories.has(category)&&!profile)}>{busy?'이야기를 정리하고 있어':'오늘의 이야기 읽기'}<ArrowRight size={17}/></button><small>한 번 읽은 이야기는 오늘 동안 유지돼. 다시 읽을 때 멸치를 더 받지 않아.</small></form>}</>}
 </section>;
}
